version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bank_fraud_db
    restart: always
    environment:
      POSTGRES_USER: postgrel
      POSTGRES_PASSWORD: 6304990878purna
      POSTGRES_DB: BankFraudSystem
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: bank_fraud_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://postgrel:6304990878purna@postgres:5432/BankFraudSystem
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: bank_fraud_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
